import Head from 'next/head';
import KeyPath from '../components/KeyPath';
import Number from '../components/Number';
import Predictions from '../components/Predictions';
import TextProvider from '../context/TextContext';

const keys = [
	{ key: 1, text: '-' },
	{ key: 2, text: 'abc' },
	{ key: 3, text: 'def' },
	{ key: 4, text: 'ghi' },
	{ key: 5, text: 'jkl' },
	{ key: 6, text: 'mno' },
	{ key: 7, text: 'pqrs' },
	{ key: 8, text: 'tuv' },
	{ key: 9, text: 'wxyz' },
	{ key: 0, text: '-' },
];

export default function Home() {
	return (
		<>
			<Head>
				<title>Predictive Text</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<TextProvider>
        
        <Predictions />
				<KeyPath>
					{keys.map(({ key, text }, idx) => {
						return (
							<Number key={idx} num={key}>
								{text}
							</Number>
						);
					})}
				</KeyPath>
			</TextProvider>
		</>
	);
}
